libao_lib = static_library(
    'ao',
    files(
        'audio_out.c',
        'audio_out_null.c',
        'audio_out_float.c',
        'audio_out_oss.c',
        'audio_out_solaris.c',
        'audio_out_al.c',
        'audio_out_win.c',
        'audio_out_wav.c',
        'audio_out_aif.c',
        'audio_out_peak.c',
        'convert2s16.c',
        'audio_out_internal.h',
    ) + config_h,
    c_args: project_args,
    include_directories: incdir,
    dependencies: m_dep,
    install: false,
)
